name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install QGIS
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-qgis qgis
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    
    - name: Test with pytest
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest 