name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install QGIS and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-qgis qgis xvfb
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    
    - name: Run tests with xvfb
      run: |
        export PYTHONPATH="/usr/share/qgis/python:${PYTHONPATH}"
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" pytest 